export { getStack, isContentstackConfigured } from './client';
export type {
  ContentstackImage,
  ContentstackEntry,
  CarEntry,
  CarSpecifications,
  TaxonomyReference,
  CarVariant,
  TaxonomyItem,
  HeaderEntry,
  HeaderLogo,
  NavigationItem,
  FooterEntry,
  FooterLink,
  FooterLinkSection,
  FooterSocialLink,
  BannerEntry,
  BannerCTA,
  HeroBanner,
  PromotionalBanner,
  PopularSearch,
  SearchSection,
  StatItem,
  StatsSection,
  ReviewEntry,
  RatingBreakdown,
  NewsEntry,
  NewsCategory,
} from './client';
export {
  fetchCars,
  fetchCarByUid,
  fetchCarBySlug,
  fetchCarVariants,
  fetchFeaturedCars,
  fetchTaxonomy,
  fetchBrands,
  fetchCities,
  searchCars,
  fetchHeader,
  fetchFooter,
  fetchBanner,
  fetchReviews,
  fetchReviewBySlug,
  fetchReviewByUid,
  fetchFeaturedReviews,
  fetchNews,
  fetchNewsBySlug,
  fetchNewsByUid,
  fetchFeaturedNews,
  fetchBreakingNews,
  fetchNewsByCategory,
} from './queries';
export type { FetchCarsParams, FetchReviewsParams, FetchNewsParams, PaginatedResponse, NewsResult } from './queries';
